# Generated by Django 3.0.6 on 2021-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team_teamfootprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.CharField(default='Project Relive', max_length=30),
        ),
    ]
